### ISSUE TITLE
Do you have code for your SDMP+DINO experiments results?

### ISSUE THREAD

**Issue by ZhuWenjie98** [OliverRensu/SDMP#1]
Hi Resu,
I noticed that your repository has implemented your data mix strategy based on MoCo V3, do you have code for your DINO experiments?

**Comment by PushparajaMurugan** [comment]
@ZhuWenjie98  Hi. Did you manage to implement SDMP + DINO?
@OliverRensu  I'm wondering how did you implement your idea in DINO? Are you planning to publish the code.?
